package io.github.brrenat.seekervault.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class SeekerColors(
    val primaryText: Color,
    val dim: Color,
    val errorText: Color,
    val lime: Color,
    val onLime: Color,
    val limeContainer: Color,
    val onLimeContainer: Color,
    val orange: Color,
    val onOrange: Color,
    val tertiaryAction: Color,
    val onTertiaryAction: Color,
    val orangeContainer: Color,
    val onOrangeContainer: Color,
    val tangerineChip: Color,
    val onTangerineChip: Color,
    val blueChip: Color,
    val onBlueChip: Color,
    val violetChip: Color,
    val onVioletChip: Color,
    val tealChip: Color,
    val onTealChip: Color,
    val pinkChip: Color,
    val onPinkChip: Color,
    val sandChip: Color,
    val onSandChip: Color,
    val surface0: Color,
    val surface1: Color,
    val surface2: Color,
    val surface3: Color,
    val destructive: Color,
    val onDestructive: Color,
    val destructiveContainer: Color,
    val onDestructiveContainer: Color,
)

internal val DarkSeekerColors =
    SeekerColors(
        primaryText = Color(0xFFE7FC6E),
        dim = Color(0xFF0A0A0A),
        errorText = Color(0xFFF83959),
        lime = Color(0xFFE7FC6E),
        onLime = Color(0xFF1B1B1B),
        limeContainer = Color(0xFFC2E60F),
        onLimeContainer = Color(0xFF1B1B1B),
        orange = Color(0xFFFFB27A),
        onOrange = Color(0xFF2E1200),
        tertiaryAction = Color(0xFF8A3C00),
        onTertiaryAction = Color(0xFFFFFFFF),
        orangeContainer = Color(0xFFFF7A1A),
        onOrangeContainer = Color(0xFF2E1200),
        tangerineChip = Color(0xFFFF7A1A),
        onTangerineChip = Color(0xFF2E1200),
        blueChip = Color(0xFF7EC8FF),
        onBlueChip = Color(0xFF00243D),
        violetChip = Color(0xFFC9A7FF),
        onVioletChip = Color(0xFF241042),
        tealChip = Color(0xFF4FDCC0),
        onTealChip = Color(0xFF00312A),
        pinkChip = Color(0xFFFF8FA8),
        onPinkChip = Color(0xFF3D0014),
        sandChip = Color(0xFFE3CF95),
        onSandChip = Color(0xFF322400),
        surface0 = Color(0xFF121212),
        surface1 = Color(0xFF1C1C1C),
        surface2 = Color(0xFF232323),
        surface3 = Color(0xFF2E2E2E),
        destructive = Color(0xFFF83959),
        onDestructive = Color(0xFF2B0008),
        destructiveContainer = Color(0xFF4D0011),
        onDestructiveContainer = Color(0xFFFFD9DE),
    )

internal val LightSeekerColors =
    SeekerColors(
        primaryText = Color(0xFF4F5C00),
        dim = Color(0xFFCFCFD2),
        errorText = Color(0xFFC4142F),
        lime = Color(0xFFF1FFA0),
        onLime = Color(0xFF1B1B1B),
        limeContainer = Color(0xFFE9FF7A),
        onLimeContainer = Color(0xFF2C3400),
        orange = Color(0xFF8A3C00),
        onOrange = Color(0xFFFFFFFF),
        tertiaryAction = Color(0xFF8A3C00),
        onTertiaryAction = Color(0xFFFFFFFF),
        orangeContainer = Color(0xFFFFE0C2),
        onOrangeContainer = Color(0xFF4A2600),
        tangerineChip = Color(0xFFFF7A1A),
        onTangerineChip = Color(0xFF2E1200),
        blueChip = Color(0xFF7EC8FF),
        onBlueChip = Color(0xFF00243D),
        violetChip = Color(0xFFC9A7FF),
        onVioletChip = Color(0xFF241042),
        tealChip = Color(0xFF4FDCC0),
        onTealChip = Color(0xFF00312A),
        pinkChip = Color(0xFFFF8FA8),
        onPinkChip = Color(0xFF3D0014),
        sandChip = Color(0xFFE3CF95),
        onSandChip = Color(0xFF322400),
        surface0 = Color(0xFFF7F7F7),
        surface1 = Color(0xFFFFFFFF),
        surface2 = Color(0xFFEEEEEE),
        surface3 = Color(0xFFE4E4E4),
        destructive = Color(0xFFF83959),
        onDestructive = Color(0xFF2B0008),
        destructiveContainer = Color(0xFFFFE1E5),
        onDestructiveContainer = Color(0xFF5C0014),
    )

internal val DarkColorScheme: ColorScheme =
    darkColorScheme(
        primary = DarkSeekerColors.lime,
        onPrimary = DarkSeekerColors.onLime,
        primaryContainer = DarkSeekerColors.limeContainer,
        onPrimaryContainer = DarkSeekerColors.onLimeContainer,
        secondary = DarkSeekerColors.pinkChip,
        onSecondary = DarkSeekerColors.onPinkChip,
        secondaryContainer = DarkSeekerColors.pinkChip,
        onSecondaryContainer = DarkSeekerColors.onPinkChip,
        tertiary = DarkSeekerColors.orange,
        onTertiary = DarkSeekerColors.onOrange,
        tertiaryContainer = DarkSeekerColors.orangeContainer,
        onTertiaryContainer = DarkSeekerColors.onOrangeContainer,
        error = DarkSeekerColors.destructive,
        onError = DarkSeekerColors.onDestructive,
        errorContainer = DarkSeekerColors.destructiveContainer,
        onErrorContainer = DarkSeekerColors.onDestructiveContainer,
        background = DarkSeekerColors.surface0,
        onBackground = Color(0xFFFFFFFF),
        surface = DarkSeekerColors.surface0,
        onSurface = Color(0xFFFFFFFF),
        surfaceVariant = DarkSeekerColors.surface2,
        onSurfaceVariant = Color(0xFFCACACA),
        outline = Color(0xFF6F6F6F),
        outlineVariant = Color(0xFF3A3A3A),
        surfaceContainerLowest = DarkSeekerColors.surface0,
        surfaceContainerLow = DarkSeekerColors.surface1,
        surfaceContainer = DarkSeekerColors.surface1,
        surfaceContainerHigh = DarkSeekerColors.surface2,
        surfaceContainerHighest = DarkSeekerColors.surface3,
        surfaceBright = DarkSeekerColors.surface3,
        surfaceDim = DarkSeekerColors.dim,
        inverseSurface = LightSeekerColors.surface0,
        inverseOnSurface = Color(0xFF1B1B1B),
        inversePrimary = LightSeekerColors.primaryText,
        scrim = DarkSeekerColors.dim,
        surfaceTint = Color.Transparent,
        primaryFixed = DarkSeekerColors.lime,
        primaryFixedDim = DarkSeekerColors.limeContainer,
        onPrimaryFixed = DarkSeekerColors.onLime,
        onPrimaryFixedVariant = DarkSeekerColors.onLimeContainer,
        secondaryFixed = DarkSeekerColors.pinkChip,
        secondaryFixedDim = DarkSeekerColors.pinkChip,
        onSecondaryFixed = DarkSeekerColors.onPinkChip,
        onSecondaryFixedVariant = DarkSeekerColors.onPinkChip,
        tertiaryFixed = DarkSeekerColors.orange,
        tertiaryFixedDim = DarkSeekerColors.orangeContainer,
        onTertiaryFixed = DarkSeekerColors.onOrange,
        onTertiaryFixedVariant = DarkSeekerColors.onOrangeContainer,
    )

internal val LightColorScheme: ColorScheme =
    lightColorScheme(
        primary = LightSeekerColors.lime,
        onPrimary = LightSeekerColors.onLime,
        primaryContainer = LightSeekerColors.limeContainer,
        onPrimaryContainer = LightSeekerColors.onLimeContainer,
        secondary = LightSeekerColors.pinkChip,
        onSecondary = LightSeekerColors.onPinkChip,
        secondaryContainer = LightSeekerColors.pinkChip,
        onSecondaryContainer = LightSeekerColors.onPinkChip,
        tertiary = LightSeekerColors.orange,
        onTertiary = LightSeekerColors.onOrange,
        tertiaryContainer = LightSeekerColors.orangeContainer,
        onTertiaryContainer = LightSeekerColors.onOrangeContainer,
        error = LightSeekerColors.destructive,
        onError = LightSeekerColors.onDestructive,
        errorContainer = LightSeekerColors.destructiveContainer,
        onErrorContainer = LightSeekerColors.onDestructiveContainer,
        background = LightSeekerColors.surface0,
        onBackground = Color(0xFF1B1B1B),
        surface = LightSeekerColors.surface0,
        onSurface = Color(0xFF1B1B1B),
        surfaceVariant = LightSeekerColors.surface2,
        onSurfaceVariant = Color(0xFF45464A),
        outline = Color(0xFF76767F),
        outlineVariant = Color(0xFFC6C6C9),
        surfaceContainerLowest = LightSeekerColors.surface1,
        surfaceContainerLow = LightSeekerColors.surface1,
        surfaceContainer = LightSeekerColors.surface1,
        surfaceContainerHigh = LightSeekerColors.surface2,
        surfaceContainerHighest = LightSeekerColors.surface3,
        surfaceBright = LightSeekerColors.surface1,
        surfaceDim = LightSeekerColors.dim,
        inverseSurface = DarkSeekerColors.surface1,
        inverseOnSurface = Color(0xFFFFFFFF),
        inversePrimary = DarkSeekerColors.lime,
        scrim = LightSeekerColors.dim,
        surfaceTint = Color.Transparent,
        primaryFixed = LightSeekerColors.lime,
        primaryFixedDim = LightSeekerColors.limeContainer,
        onPrimaryFixed = LightSeekerColors.onLime,
        onPrimaryFixedVariant = LightSeekerColors.onLimeContainer,
        secondaryFixed = LightSeekerColors.pinkChip,
        secondaryFixedDim = LightSeekerColors.pinkChip,
        onSecondaryFixed = LightSeekerColors.onPinkChip,
        onSecondaryFixedVariant = LightSeekerColors.onPinkChip,
        tertiaryFixed = LightSeekerColors.orange,
        tertiaryFixedDim = LightSeekerColors.orangeContainer,
        onTertiaryFixed = LightSeekerColors.onOrange,
        onTertiaryFixedVariant = LightSeekerColors.onOrangeContainer,
    )
